[package]
name = "daily_coding_problem"
version = "0.1.0"
authors = ["tanakakz <tanakakz.feb.23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"
itertools = "0.10.0"
